---
default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args:
          - --branch=master
          - --branch=main

  - repo: local
    hooks:
      - id: gitlint
        name: gitlint
        language: python
        additional_dependencies:
          - "gitlint-core >= 0.19.1"
        entry: gitlint
        args: [--staged, --msg-filename]
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        stages: [commit]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: f42857794802b6a77b0e66f08803575aa80d3c8f # frozen: v0.4.7
    hooks:
      - id: ruff
        files: ^.+\.py$
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        files: ^.+\.py$

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        # Bandit does not need to run on test code
        exclude: ^tests/

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.30.0
    hooks:
      - id: yamllint

  - repo: https://github.com/btford/write-good
    rev: v1.0.8
    hooks:
      - id: write-good

  - repo: https://github.com/rhysd/actionlint
    rev: ea8102762106cdca9c88829f1295b39a544706f3 # frozen: v1.6.26
    hooks:
      - id: actionlint
