---
default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: c4a0b883114b00d8d76b479c820ce7950211c99b # frozen: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args:
          - --branch=master
          - --branch=main

  - repo: https://github.com/jorisroovers/gitlint
    rev: acc9d9de6369b76d22cb4167029d2035e8730b98 # frozen: v0.19.1
    hooks:
      - id: gitlint

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: f12edd9c7be1c20cfa42420fd0e6df71e42b51ea # frozen: v4.0.0-alpha.8
    hooks:
      - id: prettier
        stages: [commit]

  - repo: https://github.com/ambv/black
    rev: ec91a2be3c44d88e1a3960a4937ad6ed3b63464e # frozen: 23.12.1
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 7d37d9032d0d161634be4554273c30efd4dea0b3 # frozen: 7.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=88"]

  - repo: https://github.com/pycqa/bandit
    rev: f3a18ab30bc444e62d02505419ab7059cead0853 # frozen: 1.7.6
    hooks:
      - id: bandit
        # Bandit does not need to run on test code
        exclude: ^tests/

  - repo: https://github.com/pycqa/pydocstyle
    rev: 07f6707e2c5612960347f7c00125620457f490a7 # frozen: 6.3.0
    hooks:
      - id: pydocstyle

  - repo: https://github.com/adrienverge/yamllint
    rev: 8713140e99914c0cb6e07364daedfb140847c3c5 # frozen: v1.33.0
    hooks:
      - id: yamllint

  - repo: https://github.com/btford/write-good
    rev: ab66ce10136dfad5146e69e70f82a3efac8842c1 # frozen: v1.0.8
    hooks:
      - id: write-good
